apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: caretta
spec:
  destination:
    namespace: caretta
    server: https://kubernetes.default.svc
  source:
    repoURL: https://helm.groundcover.com/
    targetRevision: "*"
    chart: caretta
    helm:
      values: |-
        annotations:
          tailscale.com/expose: "true"
          tailscale.com/hostname: "caretta"
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - CreateNamespace=true
