apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  source:
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: "*"
    chart: grafana
    helm:
      values: |-
        admin:
          existingSecret: grafana-admin
          passwordKey: admin-password
        grafana.ini:
          server:
            root_url: https://grafana.tail2e3bd2.ts.net/
        service:
          annotations:
            tailscale.com/expose: "true"
            tailscale.com/hostname: "grafana"
        plugins:
          - hamedkarbasi93-kafka-datasource
        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: kafka
                type: hamedkarbasi93-kafka-datasource
                access: proxy
                isDefault: true
                jsonData:
                  bootstrapServers: "dfr-kafka-kafka-bootstrap.kafka.svc:9092"
        persistence:
          enabled: true
          size: 4Gi
          storageClassName: longhorn
  project: default
  syncPolicy:
    automated:
      enabled: true
      prune: true
    syncOptions:
      - CreateNamespace=true
