apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
spec:
  destination:
    namespace: grafana
    server: https://kubernetes.default.svc
  source:
    path: ''
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 10.5.15
    chart: grafana
    helm:
      valueFiles: []
      values: |-
        grafana.ini:
          server:
            root_url: https://grafana.tail2e3bd2.ts.net/
        service:
          annotations:
            tailscale.com/expose: "true"
            tailscale.com/hostname: "grafana"
        plugins:
          - hamedkarbasi93-kafka-datasource
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
      enabled: true
    syncOptions:
      - CreateNamespace=true
